default: all

# set (NASL_VERSION_MAJOR 9)
# set (NASL_VERSION_MINOR 1)
# set (NASL_VERSION_PATCH 0)
# set (NASL_VERSION_STRING "${NASL_VERSION_MAJOR}.${NASL_VERSION_MINOR}${NASL_VERSION_SUFFIX}")
# set (NASL_PACKAGE_VERSION "${NASL_VERSION_STRING}${PROJECT_VERSION_GIT}")
# set (NASL_VERSION "${NASL_VERSION_STRING}")

# Requires.private: glib-2.0 >= 2.42.1, gio-2.0 >= 2.42.1, gnutls >= 3.2.15
	# zlib >= 1.2.8, , uuid >= 2.25.0

# pkg_check_modules (GLIB REQUIRED glib-2.0>=2.42)
# pkg_check_modules (GIO REQUIRED gio-2.0)
# pkg_check_modules (GNUTLS REQUIRED gnutls>=3.2.15)
# pkg_check_modules (LIBGVM_BASE REQUIRED libgvm_base>=1.0.0)
# pkg_check_modules (LIBGVM_UTIL REQUIRED libgvm_util>=1.0.0)

# pkg_check_modules (OPENVAS_WMICLIENT libopenvas_wmiclient>=1.0.1)
# pkg_check_modules (OPENVAS_WINCMD libopenvas_wincmd>=1.0.1)

# pkg_check_modules (LIBSSH REQUIRED libssh>=0.6.0)
# find_library (KSBA ksba)

# if (SNMP)
#   add_definitions (-DHAVE_NETSNMP)
# endif (SNMP)

all:
	python3 ./build.py